version: 1.15.0.{build}
branches:
    only:
        - master
skip_tags: true
clone_folder: C:\Cube\Cube.Core
image: Visual Studio 2017
nuget:
    project_feed: true
    disable_publish_on_pr: true
platform: Any CPU
configuration: Release
before_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - rake restore
build:
    parallel: true
    project: Cube.Core.sln
    publish_nuget: true
    verbosity: minimal
test_script:
    - >
      ..\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe
      -log:Error
      -register:user
      -target:nunit3-console.exe
      -targetargs:Cube.Core.Tests.dll
      -targetdir:"Tests\bin\Any CPU\Release\net45"
      -returntargetcode
      -hideskipped:All
      -output:CoverResults.xml
      -filter:"+[Cube*]* -[*]*NativeMethods -[*]*Properties.*"
after_test:
    - xcopy /q /Y /I "Tests\bin\Any CPU\Release\net45\Cube.Core.Tests.log" TestLog\
    - xcopy /q /Y /I CoverResults.xml TestLog\
    - pip install codecov
    - codecov -f CoverResults.xml
artifacts:
    - path: TestLog
