version: 1.14.0.{build}
branches:
    only:
        - master
skip_tags: true
clone_folder: C:\Cube\Cube.Xui
image: Visual Studio 2017
nuget:
    project_feed: true
    disable_publish_on_pr: true
platform: Any CPU
configuration: Release
before_build:
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget sources add -name Cube.FileSystem -source https://ci.appveyor.com/nuget/cube.filesystem
    - nuget restore Cube.Xui.sln
build:
    parallel: true
    project: Cube.Xui.sln
    publish_nuget: true
    verbosity: minimal
test_script:
    - >
      ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
      -log:Error
      -register:user
      -target:nunit3-console.exe
      -targetargs:Cube.Xui.Tests.dll
      -targetdir:Tests\bin\Release
      -returntargetcode
      -hideskipped:All
      -output:CoverResults.xml
      -filter:"+[Cube*]* -[*]*NativeMethods -[*]*Properties.*"
after_test:
    - xcopy /q /Y /I Tests\bin\Release\Cube.Xui.Tests.log Tests\
    - xcopy /q /Y /I CoverResults.xml Tests\
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f CoverResults.xml
artifacts:
    - path: Tests
