# --------------------------------------------------------------------------- #
# general configuration
# --------------------------------------------------------------------------- #

# version format
version: 1.4.1.{build}

# branches to build
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# --------------------------------------------------------------------------- #
# environment configuration
# --------------------------------------------------------------------------- #

# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: c:\cube\cube.core

# --------------------------------------------------------------------------- #
# build configuration
# --------------------------------------------------------------------------- #

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
    - nuget restore Cube.Core.sln

build: 
  parallel: true
  project: Cube.Core.sln
  verbosity: normal

# --------------------------------------------------------------------------- #
# tests configuration
# --------------------------------------------------------------------------- #

after_test:
    - ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:"Cube.Core.Tests.dll" -targetdir:".\Tests\bin\Release" -hideskipped:All -output:CoverResult.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "CoverResult.xml" -t d529004f-000c-400d-98e9-cd5d27dae6cc