# --------------------------------------------------------------------------- #
# general configuration
# --------------------------------------------------------------------------- #
version: 1.4.1.{build}
branches:
  except:
    - net35
skip_tags: true

# --------------------------------------------------------------------------- #
# build configuration
# --------------------------------------------------------------------------- #
clone_folder: c:\cube\cube.core
image: Visual Studio 2017
platform: Any CPU
configuration: Release
before_build:
    - nuget restore Cube.Core.sln
build: 
  parallel: true
  project: Cube.Core.sln
  publish_nuget: true
  verbosity: normal

# --------------------------------------------------------------------------- #
# tests configuration
# --------------------------------------------------------------------------- #
after_test:
    - ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:"Cube.Core.Tests.dll" -targetdir:".\Tests\bin\Release" -hideskipped:All -output:CoverResult.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "CoverResult.xml" -t d529004f-000c-400d-98e9-cd5d27dae6cc
    